var fs   = require('fs');
var base = require('path').basename;
var glob = require('glob');

function toUpper(a) {
    return a.toUpperCase();
}

function getName(file) {
    return file
        .substr(0, file.length - 4)     // remove extension
        .replace(/-[0-9]+/, '')         // remove numbers
        .replace(/([^a-z0-9])+/gi, '-') // replace non a-z with minus
        .replace(/^-+|-+$/g, '')        // trim minus
        + file.substr(-4);              // add extension
}

function getTitle(name) {
    return name
        .substr(0, name.length - 4)     // remove extension
        .replace(/-/g, ' ')             // separate words with spaces
        .replace(/(?:\b)\w/g, toUpper); // capitalize words
}

function makeCharacter(char) {
    var name = getName(char);
    return {
        src: 'src/' + char,
        img: 'img/' + name,
        title: getTitle(name)
    };
}

function makeCopy(entry) {
    fs.writeFileSync(entry.img, fs.readFileSync(entry.src));
    return entry;
}

function jsonp(eightbit) {
    return '/* This file was generated by build.js */\n' +
        'var eightbit = ' + JSON.stringify(eightbit, null, 2) + ';';
}

function svg(eightbit) {
    var w = 500;
    var ns = 'xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"';
    var svg = '<svg width="$w" height="$h" $ns>\n'
        .replace(/\$w/g, w * 27)
        .replace(/\$h/g, w * 26)
        .replace('$ns', ns);
    eightbit.forEach(function(char, index) {
        var base64 = new Buffer(fs.readFileSync(char.img)).toString('base64');
        svg += '  <image x="$x" y="$y" width="$w" height="$w" xlink:href="data:image/jpeg;base64,$b"/>\n'
            .replace(/\$w/g, w)
            .replace('$x', (index % 27) * w)
            .replace('$y', parseInt(index / 27, 10) * w)
            .replace('$b', base64);
    });
    return svg + '</svg>';
}

var eightbit = glob.sync('src/*.jpg').map(base).map(makeCharacter).map(makeCopy);

fs.writeFileSync('eightbit.jsonp', jsonp(eightbit));
fs.writeFileSync('eightbit.svg', svg(eightbit));
