var fs   = require('fs');
var base = require('path').basename;
var glob = require('glob');

function toUpper(a) {
    return a.toUpperCase();
}

function getName(file) {
    return file
        .substr(0, file.length - 4)     // remove extension
        .replace(/-[0-9]+/, '')         // remove numbers
        .replace(/([^a-z0-9])+/gi, '-') // replace non a-z with minus
        .replace(/^-+|-+$/g, '')        // trim minus
        + file.substr(-4);              // add extension
}

function getTitle(name) {
    return name
        .substr(0, name.length - 4)     // remove extension
        .replace(/-/g, ' ')             // separate words with spaces
        .replace(/(?:\b)\w/g, toUpper); // capitalize words
}

function makeEntry(src) {
    var name = getName(src);
    return {
        src: 'src/' + src,
        img: 'img/' + name,
        title: getTitle(name)
    };
}

function makeCopy(entry) {
    fs.writeFileSync(entry.img, fs.readFileSync(entry.src));
    return entry;
}

function jsonp(eightbit) {
    return '/* This file was generated by build.js */\n' +
        'var eightbit = ' + JSON.stringify(eightbit, null, 2) + ';';
}

var eightbit = glob.sync('src/*.jpg').map(base).map(makeEntry).map(makeCopy);
fs.writeFileSync('eightbit.jsonp', jsonp(eightbit));
